### ISSUE TITLE
Make a figma for the edit profile section

### ISSUE THREAD

**Issue by CodeItQuick** [CodeItQuick/VWS-Open-Source#102]
A figma needs to be created for the user profile section. We really just need functionality to change passwords easily. Don't include things like user profile pictures, as that adds extra work that isn't part of the MVP.

This figma is blocking task: #95

**Comment by Fiikayo** [comment]
https://www.figma.com/file/gT4KzK9MF7dYnQ58mgAEqH/VWS?node-id=0%3A1 all done
